import catalogData from '../data/agentCatalog.json';

/**
 * The HIVE specialist-agent catalog. Lightweight metadata (no persona body) for
 * the browser: the Agent Library browse view and the specialist chips on task
 * cards. The full persona text lives only in the DB (table `agents_catalog`,
 * seeded from scripts/agentCatalog.full.json), where the worker edge function
 * reads it to assume the specialist's voice. Generated by
 * scripts/build-agent-catalog.mjs — do not hand-edit src/data/agentCatalog.json.
 */

export interface AgentMeta {
  slug: string;
  name: string;
  division: string;
  subdivision: string | null;
  emoji: string;
  vibe: string;
  description: string;
  source: string; // which MIT collection it came from (see agentCatalog.SOURCES.md)
  tags: string[];
}

export const AGENT_CATALOG: AgentMeta[] = catalogData as AgentMeta[];

const BY_SLUG = new Map(AGENT_CATALOG.map((a) => [a.slug, a]));

/** Look up one specialist by slug, or null if unknown. */
export function agentBySlug(slug: string | null | undefined): AgentMeta | null {
  return slug ? BY_SLUG.get(slug) ?? null : null;
}

/** Distinct divisions, in catalog order, with their agent counts. */
export function divisions(): { division: string; count: number }[] {
  const counts = new Map<string, number>();
  for (const a of AGENT_CATALOG) counts.set(a.division, (counts.get(a.division) ?? 0) + 1);
  return [...counts.entries()].map(([division, count]) => ({ division, count }));
}

/** Human label for a division slug ("game-development" -> "Game Development"). */
export function divisionLabel(division: string): string {
  return division.replace(/-/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
}

/** Substring search over name, division, description, and vibe (case-insensitive). */
export function searchAgents(query: string, division?: string | null): AgentMeta[] {
  const q = query.trim().toLowerCase();
  return AGENT_CATALOG.filter((a) => {
    if (division && a.division !== division) return false;
    if (!q) return true;
    return (
      a.name.toLowerCase().includes(q) ||
      a.division.toLowerCase().includes(q) ||
      a.description.toLowerCase().includes(q) ||
      a.vibe.toLowerCase().includes(q)
    );
  });
}
